# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/Rodrigo/Projeto1/Projeto1.srcs/sources_1/new/Projeto1.vhd
read_xdc T:/Rodrigo/Projeto1/Projeto1.srcs/constrs_1/imports/Projetos/SevenSegmentos.xdc
set_property used_in_implementation false [get_files T:/Rodrigo/Projeto1/Projeto1.srcs/constrs_1/imports/Projetos/SevenSegmentos.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/Rodrigo/Projeto1/Projeto1.cache/wt [current_project]
set_property parent.project_dir T:/Rodrigo/Projeto1 [current_project]
synth_design -top Projeto1 -part xc7a100tcsg324-1
write_checkpoint Projeto1.dcp
report_utilization -file Projeto1_utilization_synth.rpt -pb Projeto1_utilization_synth.pb
