# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Problemas/io_basico.xdc

# Block Designs: bd/microblazer/microblazer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer || ORIG_REF_NAME==microblazer}]

# IP: bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_microblaze_0_0 || ORIG_REF_NAME==microblazer_microblaze_0_0}]

# IP: bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_dlmb_v10_0 || ORIG_REF_NAME==microblazer_dlmb_v10_0}]

# IP: bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_ilmb_v10_0 || ORIG_REF_NAME==microblazer_ilmb_v10_0}]

# IP: bd/microblazer/ip/microblazer_dlmb_bram_if_cntlr_0/microblazer_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblazer_dlmb_bram_if_cntlr_0}]

# IP: bd/microblazer/ip/microblazer_ilmb_bram_if_cntlr_0/microblazer_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblazer_ilmb_bram_if_cntlr_0}]

# IP: bd/microblazer/ip/microblazer_lmb_bram_0/microblazer_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_lmb_bram_0 || ORIG_REF_NAME==microblazer_lmb_bram_0}]

# IP: bd/microblazer/ip/microblazer_microblaze_0_axi_periph_0/microblazer_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblazer_microblaze_0_axi_periph_0}]

# IP: bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_mdm_1_0 || ORIG_REF_NAME==microblazer_mdm_1_0}]

# IP: bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_clk_wiz_1_0 || ORIG_REF_NAME==microblazer_clk_wiz_1_0}]

# IP: bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazer_rst_clk_wiz_1_100M_0}]

# IP: bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_axi_gpio_0_0 || ORIG_REF_NAME==microblazer_axi_gpio_0_0}]

# IP: bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_axi_gpio_0_1 || ORIG_REF_NAME==microblazer_axi_gpio_0_1}]

# IP: bd/microblazer/ip/microblazer_xbar_0/microblazer_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_xbar_0 || ORIG_REF_NAME==microblazer_xbar_0}]

# XDC: bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_microblaze_0_0 || ORIG_REF_NAME==microblazer_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_dlmb_v10_0 || ORIG_REF_NAME==microblazer_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_ilmb_v10_0 || ORIG_REF_NAME==microblazer_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_dlmb_bram_if_cntlr_0/microblazer_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_ilmb_bram_if_cntlr_0/microblazer_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_lmb_bram_0/microblazer_lmb_bram_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_mdm_1_0 || ORIG_REF_NAME==microblazer_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_clk_wiz_1_0 || ORIG_REF_NAME==microblazer_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_clk_wiz_1_0 || ORIG_REF_NAME==microblazer_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazer_rst_clk_wiz_1_100M_0}]

# XDC: bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazer_rst_clk_wiz_1_100M_0}]

# XDC: bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_axi_gpio_0_0 || ORIG_REF_NAME==microblazer_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_axi_gpio_0_0 || ORIG_REF_NAME==microblazer_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1_ooc.xdc

# XDC: bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_axi_gpio_0_1 || ORIG_REF_NAME==microblazer_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_axi_gpio_0_1 || ORIG_REF_NAME==microblazer_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/microblazer/ip/microblazer_xbar_0/microblazer_xbar_0_ooc.xdc

# XDC: bd/microblazer/microblazer_ooc.xdc
