# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

add_files T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/microblazer.bd
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_microblaze_0_0/microblazer_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_dlmb_v10_0/microblazer_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_ilmb_v10_0/microblazer_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_dlmb_bram_if_cntlr_0/microblazer_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_ilmb_bram_if_cntlr_0/microblazer_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_lmb_bram_0/microblazer_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_mdm_1_0/microblazer_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_clk_wiz_1_0/microblazer_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_rst_clk_wiz_1_100M_0/microblazer_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_0/microblazer_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_axi_gpio_0_1/microblazer_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all t:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/ip/microblazer_xbar_0/microblazer_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/microblazer_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/microblazer.bd]

read_vhdl -library xil_defaultlib {
  T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/bd/microblazer/hdl/microblazer_wrapper.vhd
  T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/sources_1/new/toplevel.vhd
}
read_xdc T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/constrs_1/imports/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files T:/Rodrigo/fpga/ucBasico/ucBasico.srcs/constrs_1/imports/Problemas/io_basico.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/Rodrigo/fpga/ucBasico/ucBasico.cache/wt [current_project]
set_property parent.project_dir T:/Rodrigo/fpga/ucBasico [current_project]
synth_design -top toplevel -part xc7a100tcsg324-1
write_checkpoint toplevel.dcp
report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb
