# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/Rodrigo/Aula4/Aula4.srcs/sources_1/new/Exercicio1.vhd
read_xdc T:/Rodrigo/Aula4/Aula4.srcs/constrs_1/imports/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files T:/Rodrigo/Aula4/Aula4.srcs/constrs_1/imports/Problemas/io_basico.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/Rodrigo/Aula4/Aula4.cache/wt [current_project]
set_property parent.project_dir T:/Rodrigo/Aula4 [current_project]
synth_design -top Exercicio1 -part xc7vx485tffg1157-1
write_checkpoint Exercicio1.dcp
report_utilization -file Exercicio1_utilization_synth.rpt -pb Exercicio1_utilization_synth.pb
